# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/HardwareConstrain/P1K_constr.xdc

# Block Designs: bd/design_main/design_main.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_main || ORIG_REF_NAME==design_main} -quiet] -quiet

# IP: bd/design_main/ip/design_main_processing_system7_0_0/design_main_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_main_processing_system7_0_0 || ORIG_REF_NAME==design_main_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_proc_sys_reset_0_0/design_main_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_main_proc_sys_reset_0_0 || ORIG_REF_NAME==design_main_proc_sys_reset_0_0} -quiet] -quiet

# XDC: f:/Git_repository/OurEDA/OurEDA-P1K/Fpga/OurEDA-P1K_zynq/OurEDA-P1K_zynq.gen/sources_1/bd/design_main/design_main_ooc.xdc
