# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Git_repository/OurEDA/OurEDA-P1K/Fpga/OurEDA-P1K_zynq/OurEDA-P1K_zynq.srcs/sources_1/bd/design_main/ip/design_main_processing_system7_0_0/design_main_processing_system7_0_0.xci
# IP: The module: 'design_main_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Git_repository/OurEDA/OurEDA-P1K/Fpga/OurEDA-P1K_zynq/OurEDA-P1K_zynq.gen/sources_1/bd/design_main/ip/design_main_processing_system7_0_0/design_main_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_main_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: f:/Git_repository/OurEDA/OurEDA-P1K/Fpga/OurEDA-P1K_zynq/OurEDA-P1K_zynq.srcs/sources_1/bd/design_main/ip/design_main_processing_system7_0_0/design_main_processing_system7_0_0.xci
# IP: The module: 'design_main_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Git_repository/OurEDA/OurEDA-P1K/Fpga/OurEDA-P1K_zynq/OurEDA-P1K_zynq.gen/sources_1/bd/design_main/ip/design_main_processing_system7_0_0/design_main_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_main_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
