#ifndef __PL_DEVICE_
#define __PL_DEVICE_

//LED
#define AXI_LED      XPAR_LED_0_S00_AXI_BASEADDR
#define LED0		 LED_S00_AXI_SLV_REG0_OFFSET
#define LED1		 LED_S00_AXI_SLV_REG1_OFFSET
#define LED2		 LED_S00_AXI_SLV_REG2_OFFSET

//GPIO
#define AXI_GPIO_ID XPAR_AXI_GPIO_0_DEVICE_ID
XGpio  axi_gpio_inst;

//UART
static XIntc Intc;          //中断控制器实例
static XUartLite Uart;      //串口实例
#define UART_DEVICE_ID XPAR_UARTLITE_0_DEVICE_ID     //串口器件ID
#define UART_INTR_ID   XPAR_INTC_0_UARTLITE_0_VEC_ID //串口中断ID
#define INTC_ID        XPAR_INTC_0_DEVICE_ID         //中断控制器ID
#define RX_NOEMPTY     XUL_SR_RX_FIFO_VALID_DATA     // 接收FIFO非空
#define Tx_EMPTY       XUL_SR_TX_FIFO_EMPTY


//PWM
#define AXI_PWM    XPAR_AXI2GPIO_0_S00_AXI_BASEADDR
#define pwm0	   AXI2GPIO_S00_AXI_SLV_REG0_OFFSET
#define pwm1	   AXI2GPIO_S00_AXI_SLV_REG1_OFFSET
#define pwm2	   AXI2GPIO_S00_AXI_SLV_REG2_OFFSET
#define pwm3	   AXI2GPIO_S00_AXI_SLV_REG3_OFFSET
#define pwm4	   AXI2GPIO_S00_AXI_SLV_REG4_OFFSET
#define pwm5	   AXI2GPIO_S00_AXI_SLV_REG5_OFFSET
#define pwm6	   AXI2GPIO_S00_AXI_SLV_REG6_OFFSET
#define pwm7	   AXI2GPIO_S00_AXI_SLV_REG7_OFFSET
#define duc0	   AXI2GPIO_S00_AXI_SLV_REG8_OFFSET
#define duc1	   AXI2GPIO_S00_AXI_SLV_REG9_OFFSET
#define duc2	   AXI2GPIO_S00_AXI_SLV_REG10_OFFSET
#define duc3	   AXI2GPIO_S00_AXI_SLV_REG11_OFFSET
#define duc4	   AXI2GPIO_S00_AXI_SLV_REG12_OFFSET
#define duc5	   AXI2GPIO_S00_AXI_SLV_REG13_OFFSET
#define duc6	   AXI2GPIO_S00_AXI_SLV_REG14_OFFSET
#define duc7	   AXI2GPIO_S00_AXI_SLV_REG15_OFFSET

//sensor
#define AXI_sensor	AXI_WT931_DECODER_BASEADDR
#define accxy		AXI_WT931_DECODER_S00_AXI_SLV_REG0_OFFSET
#define accz_rotx	AXI_WT931_DECODER_S00_AXI_SLV_REG1_OFFSET
#define rotyz		AXI_WT931_DECODER_S00_AXI_SLV_REG2_OFFSET
#define eulxy		AXI_WT931_DECODER_S00_AXI_SLV_REG3_OFFSET
#define eulz_magx	AXI_WT931_DECODER_S00_AXI_SLV_REG4_OFFSET
#define magyz		AXI_WT931_DECODER_S00_AXI_SLV_REG5_OFFSET
#define temp_h		AXI_WT931_DECODER_S00_AXI_SLV_REG6_OFFSET


//delay
#define DELAY_10_SECONDS	10000UL
#define DELAY_1_SECOND		1000UL
#define DELAY_500m_SECOND   500UL
#define DELAY_100m_SECOND	100UL
#define DELAY_50m_SECOND	50UL
#define DELAY_10m_SECOND	10UL
#define DELAY_5m_SECOND	    5UL
#define DELAY_3m_SECOND	    3UL
#define DELAY_1m_SECOND		1UL



#endif
